# db-config
host: 47.110.151.136
user: vue_shop
password: 5istudy_shop
port: 3306
database: vue_shop
---
# excel-path
excel_path_1 : ../test_data/test_data_1.xls
excel_path : ../test_data/test_data.xls
---
# upload-path
#upload-path : ../upload_file